### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by Felli**

### CODE REVIEW

**Comment by NENJAK** [comment]
Hello Felli,
how is status now with this module, is it already finished?
Thanks. Nenad

**Comment by Felli** [comment]
@NENJAK this module only half works at the moment.

**Comment by NENJAK** [comment]
Hi,
Do you need maybe help in finishing it?

**Comment by Felli** [comment]
At the moment I'm only doing minor fixes, the development is on going by the developers. :+1:

**Comment by cebe** [comment]
@luke- this should be trivial to review and merge, please do so :)

**Pull request merged**
